// packages/frontend/vue/src/components/Freeform.vue
<script setup lang="ts">
import { computed } from "vue";
import { useFreeform } from "../composables/useFreeform.js";
import type { UseFreeformOptions } from "../types.js";
import FormLoader from "./FormLoader.vue";
import FreeformView from "./FreeformView.vue";

const props = defineProps<
  UseFreeformOptions & {
    class?: string;
    loadingMessage?: string;
  }
>();

const form = useFreeform(() => props);

defineSlots<{
  default?: (props: { form: typeof form }) => unknown;
  error?: (props: { error: Error }) => unknown;
  loading?: () => unknown;
}>();

const loadedForm = computed(() => {
  if (!form.manifest) {
    return null;
  }
  return form as typeof form & {
    manifest: NonNullable<typeof form.manifest>;
  };
});
</script>

<template>
  <slot v-if="$slots.default" :form="form" />

  <slot v-else-if="form.loading" name="loading">
    <FormLoader :message="loadingMessage ?? 'Loading form…'" />
  </slot>

  <slot v-else-if="form.error" name="error" :error="form.error">
    <div role="alert">{{ form.error.message }}</div>
  </slot>

  <FreeformView
    v-else-if="loadedForm"
    :form="loadedForm"
    :class="props.class"
  />
</template>

// packages/frontend/react/src/components/Freeform.tsx
"use client";

import { useFreeform } from "../hooks/useFreeform.js";
import type { FreeformProps, UseFreeformResult } from "../types.js";
import { FormLoader } from "./FormLoader.js";
import { FreeformView } from "./FreeformView.js";

export function Freeform({
  children,
  className,
  loadingMessage,
  loadingFallback,
  errorFallback = (error) => <div role="alert">{error.message}</div>,
  ...options
}: FreeformProps) {
  const form = useFreeform(options);
  const loader = loadingFallback ?? (
    <FormLoader message={loadingMessage ?? "Loading form…"} />
  );

  if (children) {
    return <>{children(form)}</>;
  }

  if (form.loading) {
    return <>{loader}</>;
  }

  if (form.error) {
    return <>{errorFallback(form.error)}</>;
  }

  if (!form.manifest) {
    return null;
  }

  return (
    <FreeformView form={form as LoadedFreeformResult} className={className} />
  );
}

type LoadedFreeformResult = UseFreeformResult & {
  manifest: NonNullable<UseFreeformResult["manifest"]>;
};
