// packages/frontend/vue/src/components/FreeformView.vue
<script setup lang="ts">
import { computed } from "vue";
import { builtinComponents } from "../renderers/builtin/index.js";
import { joinClassNames } from "../theme/mergeClassNames.js";
import { toBemModifier } from "../theme/toBemModifier.js";
import type { UseFreeformResult } from "../types.js";

const props = defineProps<{
  form: UseFreeformResult & {
    manifest: NonNullable<UseFreeformResult["manifest"]>;
  };
  class?: string;
}>();

const components = computed(() => ({
  ...builtinComponents,
  ...props.form.theme.renderers?.components,
}));

const strategy = computed(() => props.form.theme.classNameStrategy ?? "merge");
const colorScheme = computed(
  () => props.form.theme.defaults?.colorScheme ?? "system",
);

const formClassName = computed(() =>
  joinClassNames(
    props.form.theme.classNames?.form,
    strategy.value === "merge"
      ? `ff-form--${toBemModifier(props.form.manifest.form.handle)}`
      : undefined,
    strategy.value === "merge" &&
      (colorScheme.value === "light" || colorScheme.value === "dark")
      ? `ff-form--${colorScheme.value}`
      : undefined,
    props.class,
  ),
);

const currentPage = computed(
  () =>
    props.form.manifest.layout.pages[props.form.currentPageIndex] ??
    props.form.manifest.layout.pages[0] ?? { rows: [], buttons: {} },
);

const isLastPage = computed(
  () =>
    props.form.manifest.layout.pages.length === 0 ||
    props.form.currentPageIndex >= props.form.manifest.layout.pages.length - 1,
);

const isFirstPage = computed(() => props.form.currentPageIndex === 0);

function hasPresentationalContent(
  field: (typeof props.form.manifest.fields)[string],
): boolean {
  if (field.type === "image") {
    const config = (field.frontend?.config ?? {}) as { src?: string | null };
    const image = (
      field.content as { image?: { src?: string | null } } | undefined
    )?.image;
    return Boolean(image?.src || config.src);
  }

  if (field.type === "html" || field.type === "rich-text") {
    const html = field.content?.rendered?.html?.trim();
    return Boolean((props.form.allowRawHtml && html) || field.instructions);
  }

  return true;
}

function onSubmit(event: Event) {
  void props.form.handleSubmit(event);
}
</script>

<template>
  <component
    :is="components.SuccessMessage"
    v-if="form.isComplete && form.successMessage"
    :message="form.successMessage"
    :class="form.theme.classNames?.success"
  />

  <component
    :is="components.Form"
    v-else
    :form="form"
    :class="formClassName"
    :on-submit="onSubmit"
  >
    <component
      :is="components.Errors"
      v-if="form.formErrors.length > 0"
      :errors="form.formErrors"
      :class="form.theme.classNames?.errors"
      :error-class="form.theme.classNames?.error"
    />

    <component
      :is="components.Page"
      :form="form"
      :page-index="form.currentPageIndex"
      :class="
        joinClassNames(
          form.theme.classNames?.page,
          strategy === 'merge' ? `ff-page--${form.currentPageIndex}` : undefined,
        )
      "
    >
      <template v-for="row in currentPage.rows" :key="row.uid">
        <component
          :is="components.Row"
          v-if="
            row.fields.filter((handle) => {
              const field = form.manifest.fields[handle];
              return field ? hasPresentationalContent(field) : false;
            }).length > 0
          "
          :class="
            joinClassNames(
              form.theme.classNames?.row,
              strategy === 'merge'
                ? `ff-row--${
                    row.fields.filter((handle) => {
                      const field = form.manifest.fields[handle];
                      return field ? hasPresentationalContent(field) : false;
                    }).length
                  }-fields`
                : undefined,
            )
          "
        >
          <FieldRenderer
            v-for="handle in row.fields.filter((handle) => {
              const field = form.manifest.fields[handle];
              return field ? hasPresentationalContent(field) : false;
            })"
            :key="handle"
            :field="form.manifest.fields[handle]!"
            :form="form"
            :theme="form.theme"
            :renderers="form.renderers"
            :allow-raw-html="form.allowRawHtml"
          />
        </component>
      </template>
    </component>

    <CaptchaHost
      v-for="captcha in form.manifest.security.captchas ?? []"
      :key="captcha.name"
      :form="form"
      :captcha="captcha"
    />

    <component :is="components.ButtonRow" :class="form.theme.classNames?.buttons">
      <component
        :is="components.BackButton"
        v-if="!isFirstPage && currentPage.buttons?.back"
        :label="currentPage.buttons.back.label"
        :class="form.theme.classNames?.backButton"
        :disabled="form.isSubmitting"
        :on-click="() => void form.goBack()"
      />

      <component
        :is="components.NextButton"
        v-if="
          form.manifest.settings.multiPage &&
          !isLastPage &&
          currentPage.buttons?.submit
        "
        :label="currentPage.buttons.submit.label"
        :class="form.theme.classNames?.nextButton"
        :disabled="form.isSubmitting"
        :on-click="() => void form.goNext()"
      />

      <component
        :is="components.SubmitButton"
        v-if="
          (!form.manifest.settings.multiPage || isLastPage) &&
          currentPage.buttons?.submit
        "
        :label="currentPage.buttons.submit.label"
        :class="form.theme.classNames?.submitButton"
        :disabled="form.isSubmitting"
      />

      <component
        :is="components.SaveButton"
        v-if="currentPage.buttons?.save"
        :label="currentPage.buttons.save.label"
        :class="form.theme.classNames?.saveButton"
        :disabled="form.isSubmitting"
        :on-click="() => void form.saveDraft()"
      />
    </component>
  </component>
</template>

// packages/frontend/react/src/components/FreeformView.tsx
"use client";

import { builtinComponents } from "../renderers/builtin/index.js";
import { FieldRenderer } from "../renderers/FieldRenderer.js";
import { joinClassNames } from "../theme/mergeClassNames.js";
import { toBemModifier } from "../theme/toBemModifier.js";
import type { FreeformRuntime, UseFreeformResult } from "../types.js";
import { CaptchaHost } from "./CaptchaHost.js";

type LoadedFreeformResult = UseFreeformResult & {
  manifest: NonNullable<UseFreeformResult["manifest"]>;
};

type FreeformViewProps = {
  form: LoadedFreeformResult;
  className?: string;
};

function asRuntime(form: LoadedFreeformResult): FreeformRuntime {
  return form;
}

function hasPresentationalContent(
  field: NonNullable<LoadedFreeformResult["manifest"]>["fields"][string],
  allowRawHtml: boolean,
): boolean {
  if (field.type === "image") {
    const config = (field.frontend?.config ?? {}) as { src?: string | null };
    const image = (
      field.content as { image?: { src?: string | null } } | undefined
    )?.image;
    return Boolean(image?.src || config.src);
  }

  if (field.type === "html" || field.type === "rich-text") {
    const html = field.content?.rendered?.html?.trim();
    return Boolean((allowRawHtml && html) || field.instructions);
  }

  return true;
}

export function FreeformView({ form, className }: FreeformViewProps) {
  const runtime = asRuntime(form);
  const { manifest, theme, renderers, allowRawHtml } = form;
  const components = { ...builtinComponents, ...theme.renderers?.components };
  const strategy = theme.classNameStrategy ?? "merge";
  const colorScheme = theme.defaults?.colorScheme ?? "system";
  const colorSchemeClass =
    strategy === "merge" && (colorScheme === "light" || colorScheme === "dark")
      ? `ff-form--${colorScheme}`
      : undefined;
  const formHandleClass =
    strategy === "merge"
      ? `ff-form--${toBemModifier(manifest.form.handle)}`
      : undefined;
  const formClassName = joinClassNames(
    theme.classNames?.form,
    formHandleClass,
    colorSchemeClass,
    className,
  );
  const pages = manifest.layout.pages;
  const currentPage = pages[form.currentPageIndex] ??
    pages[0] ?? { rows: [], buttons: {} };
  const isLastPage =
    pages.length === 0 || form.currentPageIndex >= pages.length - 1;
  const isFirstPage = form.currentPageIndex === 0;

  if (form.isComplete && form.successMessage) {
    return (
      <components.SuccessMessage
        message={form.successMessage}
        className={theme.classNames?.success}
      />
    );
  }

  return (
    <components.Form
      form={runtime}
      className={formClassName}
      onSubmit={form.handleSubmit}
    >
      {form.formErrors.length > 0 ? (
        <components.Errors
          errors={form.formErrors}
          className={theme.classNames?.errors}
          errorClassName={theme.classNames?.error}
        />
      ) : null}

      <components.Page
        form={runtime}
        pageIndex={form.currentPageIndex}
        className={joinClassNames(
          theme.classNames?.page,
          strategy === "merge"
            ? `ff-page--${form.currentPageIndex}`
            : undefined,
        )}
      >
        {currentPage.rows.map((row) => {
          const visibleHandles = row.fields.filter((handle) => {
            const field = manifest.fields[handle];
            return field
              ? hasPresentationalContent(field, allowRawHtml)
              : false;
          });

          if (visibleHandles.length === 0) {
            return null;
          }

          return (
            <components.Row
              key={row.uid}
              className={joinClassNames(
                theme.classNames?.row,
                strategy === "merge"
                  ? `ff-row--${visibleHandles.length}-fields`
                  : undefined,
              )}
            >
              {visibleHandles.map((handle) => {
                const field = manifest.fields[handle];
                if (!field) {
                  return null;
                }

                return (
                  <FieldRenderer
                    key={field.uid}
                    field={field}
                    form={runtime}
                    theme={theme}
                    renderers={renderers}
                    allowRawHtml={allowRawHtml}
                  />
                );
              })}
            </components.Row>
          );
        })}
      </components.Page>

      {(manifest.security.captchas ?? []).map((captcha) => (
        <CaptchaHost key={captcha.name} form={runtime} captcha={captcha} />
      ))}

      <components.ButtonRow className={theme.classNames?.buttons}>
        {!isFirstPage && currentPage.buttons?.back ? (
          <components.BackButton
            label={currentPage.buttons.back.label}
            className={theme.classNames?.backButton}
            disabled={form.isSubmitting}
            onClick={() => void form.goBack()}
          />
        ) : null}

        {manifest.settings.multiPage &&
        !isLastPage &&
        currentPage.buttons?.submit ? (
          <components.NextButton
            label={currentPage.buttons.submit.label}
            className={theme.classNames?.nextButton}
            disabled={form.isSubmitting}
            onClick={() => void form.goNext()}
          />
        ) : null}

        {(!manifest.settings.multiPage || isLastPage) &&
        currentPage.buttons?.submit ? (
          <components.SubmitButton
            label={currentPage.buttons.submit.label}
            className={theme.classNames?.submitButton}
            disabled={form.isSubmitting}
          />
        ) : null}

        {currentPage.buttons?.save ? (
          <components.SaveButton
            label={currentPage.buttons.save.label}
            className={theme.classNames?.saveButton}
            disabled={form.isSubmitting}
            onClick={() => void form.saveDraft()}
          />
        ) : null}
      </components.ButtonRow>
    </components.Form>
  );
}
