// packages/frontend/vue/src/renderers/builtin/EmailField.tsx
// @ts-nocheck
import {
  type EmailSuggestionLabels,
  mountEmailSuggestions,
} from "@solspace/freeform-core";
import { defineComponent, onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { VueFieldRendererProps } from "../../types.js";
import { inputProps } from "./inputProps.js";
export const EmailFieldRenderer = defineComponent({
  name: "EmailFieldRenderer",
  props: [
    "field",
    "form",
    "value",
    "errors",
    "input",
    "classNames",
    "renderLabel",
    "renderInstructions",
    "renderErrors",
    "allowRawHtml",
  ],
  setup(props: VueFieldRendererProps) {
    const element = ref<HTMLInputElement>();
    let controller: ReturnType<typeof mountEmailSuggestions> | undefined;
    const setup = () => {
      controller?.destroy();
      controller = undefined;
      const config = props.field.frontend?.config as
        | {
            suggestEmailCorrections?: boolean;
            emailSuggestionLabels?: EmailSuggestionLabels;
          }
        | undefined;
      if (config?.suggestEmailCorrections !== true || !element.value) return;
      controller = mountEmailSuggestions(
        element.value,
        config.emailSuggestionLabels,
        (value) => props.form.setValue(props.field.handle, value),
      );
    };
    onMounted(setup);
    watch(() => JSON.stringify(props.field.frontend?.config), setup, {
      flush: "post",
    });
    watch(
      () => props.input.value,
      () => controller?.clear(),
    );
    onBeforeUnmount(() => controller?.destroy());
    return () => (
      <input
        type="email"
        class={props.classNames.input}
        {...inputProps(props)}
        ref={element}
      />
    );
  },
});

// packages/frontend/react/src/renderers/builtin/EmailField.tsx
import {
  type EmailSuggestionLabels,
  mountEmailSuggestions,
} from "@solspace/freeform-core";
import { useEffect, useRef } from "react";
import type { ReactFieldRendererProps } from "../../types.js";
import { inputProps } from "./inputProps.js";

export function EmailFieldRenderer(props: ReactFieldRendererProps) {
  const input = inputProps(props);
  const element = useRef<HTMLInputElement>(null);
  const controller =
    useRef<ReturnType<typeof mountEmailSuggestions>>(undefined);
  const current = useRef(props);
  current.current = props;
  const configKey = JSON.stringify(props.field.frontend?.config ?? {});
  useEffect(() => {
    const config = JSON.parse(configKey) as {
      suggestEmailCorrections?: boolean;
      emailSuggestionLabels?: EmailSuggestionLabels;
    };
    if (config.suggestEmailCorrections !== true || !element.current) return;
    controller.current = mountEmailSuggestions(
      element.current,
      config.emailSuggestionLabels,
      (value) =>
        current.current.form.setValue(current.current.field.handle, value),
    );
    return () => {
      controller.current?.destroy();
      controller.current = undefined;
    };
  }, [configKey]);
  // biome-ignore lint/correctness/useExhaustiveDependencies: External value changes must dismiss stale suggestions.
  useEffect(() => controller.current?.clear(), [input.value]);
  return (
    <input
      type="email"
      className={props.classNames.input}
      {...input}
      ref={element}
    />
  );
}
