// packages/frontend/react/src/renderers/builtin/CalculationField.tsx
import {
  evaluateCalculation,
  getCalculationConfig,
} from "@solspace/freeform-core";
import { useEffect, useRef } from "react";

import type { ReactFieldRendererProps } from "../../types.js";

/**
 * Live calculation field — recomputes when operand values change.
 * Matches classic Freeform ExpressionLanguage + field:handle formulas.
 */
export function CalculationFieldRenderer(props: ReactFieldRendererProps) {
  const { field, form, classNames, value } = props;
  const config = getCalculationConfig(field.frontend?.config);
  const inputType = config.inputType ?? "regularTextInput";
  const setValueRef = useRef(form.setValue);
  setValueRef.current = form.setValue;

  const _operandKey = extractOperandSnapshot(
    config.calculations ?? "",
    form.values,
  );

  useEffect(() => {
    let cancelled = false;
    const formula = config.calculations ?? "";

    void (async () => {
      const result = await evaluateCalculation(
        formula,
        form.values,
        config.decimalCount,
      );

      if (cancelled) {
        return;
      }

      const next = result == null ? "" : String(result);
      const current = form.getValue(field.handle);
      if (String(current ?? "") !== next) {
        setValueRef.current(field.handle, next);
      }
    })();

    return () => {
      cancelled = true;
    };
    // Re-run when operand values change (snapshot string), not on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional operandKey
  }, [
    field.handle,
    config.calculations,
    config.decimalCount,
    form.values,
    form.getValue,
  ]);

  const display = value == null || value === "" ? "" : String(value);

  if (inputType === "hidden") {
    return <input type="hidden" name={field.handle} value={display} readOnly />;
  }

  if (inputType === "plainText") {
    return (
      <div className={classNames.input}>
        <input type="hidden" name={field.handle} value={display} readOnly />
        <p className="ff-field__calculation-plain" data-freeform-calculation="">
          {display}
        </p>
      </div>
    );
  }

  return (
    <input
      className={classNames.input}
      type="text"
      name={field.handle}
      id={`freeform-${field.handle}`}
      value={display}
      readOnly
      aria-readonly="true"
    />
  );
}

function extractOperandSnapshot(
  calculations: string,
  values: Record<string, unknown>,
): string {
  const handles: string[] = [];
  for (const match of calculations.matchAll(/field:([a-zA-Z0-9_]+)/g)) {
    if (!handles.includes(match[1])) {
      handles.push(match[1]);
    }
  }

  return handles
    .map((handle) => `${handle}:${String(values[handle] ?? "")}`)
    .join("|");
}

// packages/frontend/vue/src/renderers/builtin/CalculationField.tsx
import {
  evaluateCalculation,
  getCalculationConfig,
} from "@solspace/freeform-core";
import { defineComponent, shallowRef, watch } from "vue";
import type { VueFieldRendererProps } from "../../types.js";

export const CalculationFieldRenderer = defineComponent({
  name: "CalculationFieldRenderer",
  props: {
    field: { type: Object, required: true },
    form: { type: Object, required: true },
    classNames: { type: Object, required: true },
    value: { required: true },
  },
  setup(props: VueFieldRendererProps) {
    const config = getCalculationConfig(props.field.frontend?.config);
    const inputType = config.inputType ?? "regularTextInput";
    const setValueRef = shallowRef(props.form.setValue);
    setValueRef.value = props.form.setValue;

    watch(
      () => [
        props.field.handle,
        config.calculations,
        config.decimalCount,
        props.form.values,
      ],
      () => {
        let cancelled = false;
        const formula = config.calculations ?? "";

        void (async () => {
          const result = await evaluateCalculation(
            formula,
            props.form.values,
            config.decimalCount,
          );

          if (cancelled) {
            return;
          }

          const next = result == null ? "" : String(result);
          const current = props.form.getValue(props.field.handle);
          if (String(current ?? "") !== next) {
            setValueRef.value(props.field.handle, next);
          }
        })();

        return () => {
          cancelled = true;
        };
      },
      { immediate: true, deep: true },
    );

    return () => {
      const display =
        props.value == null || props.value === "" ? "" : String(props.value);

      if (inputType === "hidden") {
        return (
          <input
            type="hidden"
            name={props.field.handle}
            value={display}
            readonly
          />
        );
      }

      if (inputType === "plainText") {
        return (
          <div class={props.classNames.input}>
            <input
              type="hidden"
              name={props.field.handle}
              value={display}
              readonly
            />
            <p class="ff-field__calculation-plain" data-freeform-calculation="">
              {display}
            </p>
          </div>
        );
      }

      return (
        <input
          class={props.classNames.input}
          type="text"
          name={props.field.handle}
          id={`freeform-${props.field.handle}`}
          value={display}
          readonly
          aria-readonly="true"
        />
      );
    };
  },
});
