// packages/frontend/react/src/renderers/builtin/SearchableSelect.tsx
import {
  SearchableSelect,
  type SearchableSelectConfig,
} from "@solspace/freeform-core";
import { type ReactNode, useEffect, useRef } from "react";

export function SearchableSelectWrapper({
  config,
  children,
}: {
  config: SearchableSelectConfig;
  children: ReactNode;
}) {
  const host = useRef<HTMLDivElement>(null);
  const controller = useRef<SearchableSelect | null>(null);
  const currentConfig = useRef(config);
  currentConfig.current = config;
  useEffect(() => {
    const select = host.current?.querySelector("select");
    if (!select) return;
    controller.current = new SearchableSelect(select, currentConfig.current);
    return () => {
      controller.current?.destroy();
      controller.current = null;
    };
  }, []);
  useEffect(() => {
    controller.current?.sync(config);
  });
  return <div ref={host}>{children}</div>;
}

// packages/frontend/vue/src/renderers/builtin/SearchableSelect.tsx
import {
  SearchableSelect,
  type SearchableSelectConfig,
} from "@solspace/freeform-core";
import {
  defineComponent,
  onBeforeUnmount,
  onMounted,
  onUpdated,
  type PropType,
  ref,
} from "vue";

export const SearchableSelectWrapper = defineComponent({
  name: "SearchableSelectWrapper",
  props: {
    config: {
      type: Object as PropType<SearchableSelectConfig>,
      required: true,
    },
  },
  setup(props, { slots }) {
    const host = ref<HTMLDivElement>();
    let controller: SearchableSelect | undefined;
    onMounted(() => {
      const select = host.value?.querySelector("select");
      if (select) controller = new SearchableSelect(select, props.config);
    });
    onUpdated(() => controller?.sync(props.config));
    onBeforeUnmount(() => controller?.destroy());
    return () => <div ref={host}>{slots.default?.()}</div>;
  },
});
